name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Ref name
      run: echo "${{ github.ref_name }}"
    - name: Build
      run: VERSION=$(git describe --tags --abbrev=0) make

    - name: Test
      run: go test -v ./...
