name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

# github.ref_name is either the name of the branch or the tag. 
    - name: Build
      run: VERSION="${{ github.ref_name }}" make

    - name: Test
      run: go test -v ./...
